comment:
  image:
    repository: oksidant/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: oksidant/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: oksidant/ui
    tag: latest
  service:
    externalPort: 9292
